### ISSUE TITLE
link-hint does not respect avy-all-windows

### ISSUE THREAD

**Issue by fm4d** [noctuid/link-hint.el#3] opened 2016-01-10 03:29 UTC
I am not sure if this is bug of intention but with 
```(setq avy-all-windows 'all-frames)``` link-hint only hints in current frame.

**Comment by noctuid** [comment] 2016-01-10 18:26
It was intentional, or at least I didn't bother adding support for multiple windows/frames because I've never found it useful personally.

I've added `link-hint-avy-all-windows` which you can use if you want a different value than your normal `avy-all-windows`. Otherwise, the value `avy-all-windows` will be used directly. Let me know if you encounter any problems.

**Comment by fm4d** [comment] 2016-01-10 23:38
Unfortunately value ```all-frames``` does not work, it simply ignores all links (```link-hint--find-regexp: End of buffer``` in messages). Values ```t``` (all windows in frame) and ```nil``` (selected window) works as expected.

**Comment by noctuid** [comment] 2016-01-11 00:52
@fm4d I can't reproduce this. Is it ignoring links in the current frame as well? Can you give me more details? Make sure that if you're changing values after loading link-hint that you're changing `link-hint-avy-all-windows` instead of `avy-all-windows`.

**Comment by fm4d** [comment] 2016-01-11 01:00
Well, I have both avy-all-windows and link-hint-avy-all-windows set to ```'all-frames``` and link-hint-open-link ignores links in both current frame and other frames. I would suspect some problem with EXWM + multiple monitor setup I have but avy works well like this (jumping from monitor to monitor with avy-goto-*) so it seems like your package is doing the frame collecting differently than avy ( just guessing ).

**Comment by noctuid** [comment] 2016-01-11 01:28
`link-hint-open-link` is working for me across desktops; I can't test with exwm and multiple monitors currently. I'm using the same macro avy is (`avy-dowindows`). I've tested it with the latest version of avy from melpa. Can you update avy if you're not already on the latest version? I'm guessing that won't fix the problem. It may be a problem with `link-hint--find-regexp` throwing an error with exwm. Are you getting any other messages? I can try installing and testing with exwm later this week.

**Comment by fm4d** [comment] 2016-01-11 16:18
I have the latest version of avy and no other messages are shown. I will also try to test it with different exwm settings / without exwm when I have time.

**Comment by noctuid** [comment] 2016-01-13 22:42
@fm4d I tried exwm and couldn't replicate the problem. I probably shouldn't have assumed it had anything to do with exwm. What probably happened is that one of the frames you had open was an empty buffer which was causing the error. Please try with the latest version.

**Comment by fm4d** [comment] 2016-01-14 16:14
Yes, https://github.com/noctuid/link-hint.el/commit/669886ca08933268a6a5f7cb401351ac26950857 fixed it for me. Thanks and sorry for putting you on wrong track with EXWM.

**Comment by noctuid** [comment] 2016-01-14 22:29
No problem. Glad it's working now; let me know if you have any other problems.

**Closed by noctuid** 2016-01-14 22:29 UTC
